[global]
port = 1701
access control = no
force userspace = yes

[lns default]
ip range = 10.10.0.10-10.10.0.250
local ip = 10.10.0.1
require chap = yes
refuse pap = yes
require authentication = yes
name = l2tpd
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
