#!/bin/bash
# ==========================================================================
# vpn-stack/install.sh
# Installs OpenVPN + L2TP/IPsec + a unified web panel (user/pass, per-user
# time + traffic quota, live usage) on an Iran RELAY. All client traffic
# egresses through the fleet REALITY tunnel to the foreign EXIT, so users
# get a foreign IP while connecting to a fast domestic endpoint.
#
# Run this AFTER the relay's xray dokodemo + tunnel is up (installer/iran.sh),
# because it reuses that same tunnel (same EXIT_IP + tunnel keys).
#
# Everything here is ADDITIVE and isolated: it never touches the customer
# xray relay (v2ray) service.
#
# Usage:
#   RELAY_IP=<this server public ip> EXIT_IP=<foreign exit ip> \
#   TUN_UUID=<tunnel uuid> TUN_PUB=<tunnel reality pubkey> TUN_SID=<tunnel short id> \
#   [PANEL_USER=admin] [PANEL_PASS=...] [L2TP_PSK=...] \
#   bash vpn-stack/install.sh
#
# The tunnel UUID/PUB/SID are the SAME values the relay's xray tunnel outbound
# uses (they are generated by the exit). If omitted, PANEL_PASS and L2TP_PSK
# are auto-generated and printed at the end.
# ==========================================================================
set -euo pipefail

RELAY_IP="${RELAY_IP:?set RELAY_IP=the relay public IP}"
EXIT_IP="${EXIT_IP:?set EXIT_IP=the foreign exit IP}"
TUN_UUID="${TUN_UUID:?set TUN_UUID (tunnel client uuid, from the exit)}"
TUN_PUB="${TUN_PUB:?set TUN_PUB (tunnel REALITY public key, from the exit)}"
TUN_SID="${TUN_SID:?set TUN_SID (tunnel REALITY short id, from the exit)}"
PANEL_PORT="${PANEL_PORT:-2098}"
PANEL_USER="${PANEL_USER:-admin}"
PANEL_PASS="${PANEL_PASS:-$(openssl rand -base64 9 | tr -dc 'A-Za-z0-9')}"
L2TP_PSK="${L2TP_PSK:-$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9')}"
DIR="$(cd "$(dirname "$0")" && pwd)"

echo ">> VPN stack: relay $RELAY_IP -> exit $EXIT_IP"

# --- 1) packages ---
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq openvpn easy-rsa strongswan strongswan-starter libcharon-extra-plugins \
                      xl2tpd ppp openssl curl python3 iptables dnsmasq >/dev/null
command -v /usr/local/bin/xray >/dev/null || { echo "ERROR: xray missing -- run installer/iran.sh first"; exit 1; }
[ -c /dev/net/tun ] || { echo "ERROR: /dev/net/tun missing (need KVM, not OpenVZ)"; exit 1; }

# --- 2) component files ---
mkdir -p /opt/ovpnpanel /usr/local/sbin /usr/local/etc/xray /run/l2tp-map /etc/openvpn/server
install -m755 "$DIR/tcp2socks.py"  /usr/local/sbin/tcp2socks.py
install -m755 "$DIR/dns2socks.py"  /opt/ovpnpanel/dns2socks.py
install -m755 "$DIR/ovpn-auth.py"  /opt/ovpnpanel/ovpn-auth.py
install -m755 "$DIR/accounting.py" /opt/ovpnpanel/accounting.py
install -m644 "$DIR/panel.py"      /opt/ovpnpanel/panel.py
[ -f /opt/ovpnpanel/users.json ] || echo '{}' > /opt/ovpnpanel/users.json
# OpenVPN drops to user "nobody", and auth-user-pass-verify runs AFTER that drop,
# so the auth script must be able to read the user store or every login fails with
# "external program exited with error status: 1". Give the store group-read for
# nogroup (root still owns it; nobody can read, never write).
chgrp nogroup /opt/ovpnpanel/users.json 2>/dev/null || true
chmod 640 /opt/ovpnpanel/users.json
chmod 755 /opt/ovpnpanel

subst(){ sed -e "s|__EXIT_IP__|$EXIT_IP|g; s|__RELAY_IP__|$RELAY_IP|g; s|__TUN_UUID__|$TUN_UUID|g; s|__TUN_PUB__|$TUN_PUB|g; s|__TUN_SID__|$TUN_SID|g" "$1"; }

# --- 3) OpenVPN server (username/password auth, no per-user certs) ---
if [ ! -f /etc/openvpn/server/server.crt ]; then
  rm -rf /etc/openvpn/easy-rsa; make-cadir /etc/openvpn/easy-rsa
  ( cd /etc/openvpn/easy-rsa
    export EASYRSA_BATCH=1 EASYRSA_ALGO=ec EASYRSA_CURVE=prime256v1 EASYRSA_REQ_CN=fleet-ca EASYRSA_CERT_EXPIRE=3650
    ./easyrsa init-pki >/dev/null; ./easyrsa build-ca nopass >/dev/null
    ./easyrsa gen-req server nopass >/dev/null; ./easyrsa sign-req server server >/dev/null
    openvpn --genkey secret /etc/openvpn/ta.key 2>/dev/null || openvpn --genkey --secret /etc/openvpn/ta.key
    cp pki/ca.crt pki/issued/server.crt pki/private/server.key /etc/openvpn/server/
    cp /etc/openvpn/ta.key /etc/openvpn/server/ )
fi
install -m644 "$DIR/templates/openvpn-server.conf" /etc/openvpn/server/server.conf

# --- 4) xray-ovpn: socks(:11080) -> fleet tunnel -> exit ---
subst "$DIR/templates/config-ovpn.json" > /usr/local/etc/xray/config-ovpn.json
/usr/local/bin/xray -test -c /usr/local/etc/xray/config-ovpn.json >/dev/null

# --- 5) tcp2socks + routing (10.8.0.0/24 OpenVPN, 10.10.0.0/24 L2TP -> tunnel) ---
subst "$DIR/templates/ovpn-route-up.sh" > /usr/local/sbin/ovpn-route-up.sh
chmod +x /usr/local/sbin/ovpn-route-up.sh

# --- 5b) DNS through the tunnel (avoid Iran's 10.10.34.x DNS poisoning) ---
# dnsmasq answers on the VPN gateways and forwards to dns2socks, which resolves
# via the fleet tunnel at the foreign exit. VPN clients are pushed the gateway as DNS.
PUBDEV="$(ip route show default | awk '{print $5; exit}')"
cat > /etc/dnsmasq.d/vpn-tunnel-dns.conf <<EOF
port=53
no-resolv
no-hosts
bind-dynamic
except-interface=$PUBDEV
except-interface=lo
server=127.0.0.1#5300
cache-size=1000
EOF

# --- 6) L2TP / IPsec ---
subst "$DIR/templates/ipsec.conf" > /etc/ipsec.conf
printf ': PSK "%s"\n' "$L2TP_PSK" > /etc/ipsec.secrets; chmod 600 /etc/ipsec.secrets
install -m644 "$DIR/templates/xl2tpd.conf"   /etc/xl2tpd/xl2tpd.conf
install -m644 "$DIR/templates/options.xl2tpd" /etc/ppp/options.xl2tpd
[ -f /etc/ppp/chap-secrets ] || printf "# client\tserver\tsecret\tIP\n" > /etc/ppp/chap-secrets
chmod 600 /etc/ppp/chap-secrets
# per-user accounting hooks + l2tp kernel module on boot
cat > /etc/ppp/ip-up.d/vpn-acct <<'EOF'
#!/bin/bash
[ -n "${PEERNAME:-}" ] && { mkdir -p /run/l2tp-map; echo "$PEERNAME" > "/run/l2tp-map/$PPP_IFACE"; }
EOF
cat > /etc/ppp/ip-down.d/vpn-acct <<'EOF'
#!/bin/bash
rm -f "/run/l2tp-map/$PPP_IFACE"
EOF
chmod +x /etc/ppp/ip-up.d/vpn-acct /etc/ppp/ip-down.d/vpn-acct
echo 'l2tp_ppp' > /etc/modules-load.d/l2tp.conf; modprobe l2tp_ppp 2>/dev/null || true

# --- 7) sysctl (forwarding + IPsec) ---
cat > /etc/sysctl.d/60-vpn-stack.conf <<'EOF'
net.ipv4.ip_forward=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.default.send_redirects=0
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter=0
EOF
sysctl -p /etc/sysctl.d/60-vpn-stack.conf >/dev/null 2>&1 || true

# --- 8) panel TLS cert ---
[ -f /opt/ovpnpanel/cert.pem ] || openssl req -x509 -newkey rsa:2048 -keyout /opt/ovpnpanel/key.pem \
  -out /opt/ovpnpanel/cert.pem -days 3650 -nodes -subj "/CN=$RELAY_IP" >/dev/null 2>&1

# --- 9) systemd units ---
cat > /etc/systemd/system/xray-ovpn.service <<EOF
[Unit]
Description=xray OpenVPN/L2TP egress router (socks -> fleet tunnel -> exit)
After=network.target
[Service]
ExecStart=/usr/local/bin/xray run -c /usr/local/etc/xray/config-ovpn.json
Restart=always
RestartSec=5
LimitNOFILE=1048576
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/tcp2socks.service <<EOF
[Unit]
Description=tcp2socks (transparent TCP -> fleet socks -> tunnel)
After=network.target xray-ovpn.service
Wants=xray-ovpn.service
[Service]
ExecStart=/usr/bin/python3 /usr/local/sbin/tcp2socks.py
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/dns2socks.service <<EOF
[Unit]
Description=DNS-over-tunnel resolver (UDP -> socks TCP-DNS -> exit)
After=network.target xray-ovpn.service
Wants=xray-ovpn.service
[Service]
ExecStart=/usr/bin/python3 /opt/ovpnpanel/dns2socks.py
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/ovpn-route.service <<EOF
[Unit]
Description=VPN egress routing (tcp2socks + nat)
After=tcp2socks.service xray-ovpn.service openvpn-server@server.service
Wants=tcp2socks.service xray-ovpn.service
[Service]
Type=oneshot
ExecStart=/usr/local/sbin/ovpn-route-up.sh
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/vpn-accounting.service <<EOF
[Unit]
Description=VPN per-user traffic accounting + quota enforcement
After=network.target openvpn-server@server.service
[Service]
ExecStart=/usr/bin/python3 /opt/ovpnpanel/accounting.py
Restart=always
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/ovpn-panel.service <<EOF
[Unit]
Description=Fleet VPN web panel
After=network.target
[Service]
Environment=PANEL_PORT=$PANEL_PORT
Environment=PANEL_USER=$PANEL_USER
Environment=PANEL_PASS=$PANEL_PASS
Environment=SERVER_IP=$RELAY_IP
ExecStart=/usr/bin/python3 /opt/ovpnpanel/panel.py
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
EOF

# --- 10) enable + start ---
systemctl daemon-reload
systemctl enable --now openvpn-server@server xray-ovpn tcp2socks dns2socks vpn-accounting ovpn-panel >/dev/null 2>&1
systemctl enable strongswan-starter xl2tpd >/dev/null 2>&1
systemctl restart strongswan-starter xl2tpd
systemctl restart dnsmasq
systemctl start ovpn-route
sleep 2

echo
echo "================= VPN STACK INSTALLED ================="
echo "  Panel:      https://$RELAY_IP:$PANEL_PORT/    ($PANEL_USER / $PANEL_PASS)"
echo "  OpenVPN:    port 1194/tcp, shared .ovpn from the panel, user/pass login"
echo "  L2TP/IPsec: server $RELAY_IP, PSK: $L2TP_PSK, user/pass from the panel"
echo "  Egress IP:  $EXIT_IP (foreign)"
echo "  Services:   $(for s in openvpn-server@server xray-ovpn tcp2socks vpn-accounting ovpn-panel strongswan-starter xl2tpd; do printf '%s=%s ' "$s" "$(systemctl is-active "$s")"; done)"
echo "======================================================"
